coav:
    resource: "@CoavBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# Swiftmailer Configuration
#swiftmailer:
  #  transport: "%mailer_transport%"
  #  host:      "%mailer_host%"
  #  username:  "%mailer_user%"
  #  password:  "%mailer_password%"
  #  spool:     { type: memory }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin