coav_planemodel:
    resource: "@CoavBundle/Resources/config/routing/planemodel.yml"
    prefix:   /planemodel

coav_homepage:
    path:     /
    defaults: { _controller: CoavBundle:Default:index }

coav_flight:
        resource: "@CoavBundle/Resources/config/routing/flight.yml"
        prefix:   /flight


coav_reservation:
        resource: "@CoavBundle/Resources/config/routing/reservation.yml"
        prefix:   /reservation


coav_terrain:
        resource: "@CoavBundle/Resources/config/routing/terrain.yml"
        prefix:   /terrain


