services:
#    coav.example:
#        class: CoavBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.admin.terrain:
        class: CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration des services", label: "Terrain" }
        arguments:
            - ~
            - CoavBundle\Entity\Terrain
            - ~

    app.admin.flight:
        class: CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration des services", label: "Flight" }
        arguments:
            - ~
            - CoavBundle\Entity\Flight
            - ~
    app.admin.reservation:
        class: CoavBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration des services", label: "Reservation" }
        arguments:
            - ~
            - CoavBundle\Entity\Reservation
            - ~
    app.admin.plane_model:
            class: CoavBundle\Admin\PlaneModelAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Administration des services", label: "Plane Model" }
            arguments:
                - ~
                - CoavBundle\Entity\PlaneModel
                - ~
    app.admin.user:
                class: CoavBundle\Admin\PlaneModelAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: "Administration des services", label: "Utilisateur" }
                arguments:
                    - ~
                    - CoavBundle\Entity\User
                    - ~