flight_index:
    path:     /
    defaults: { _controller: "CoavBundle:Flight:index" }
    methods:  GET

flight_show:
    path:     /{id}/show
    defaults: { _controller: "CoavBundle:Flight:show" }
    methods:  GET

flight_new:
    path:     /new
    defaults: { _controller: "CoavBundle:Flight:new" }
    methods:  [GET, POST]

flight_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoavBundle:Flight:edit" }
    methods:  [GET, POST]

flight_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoavBundle:Flight:delete" }
    methods:  DELETE

coav_flight:
        resource: "@CoavBundle/Resources/config/routing/flight.yml"
        prefix:   /flight

