reservation_index:
    path:     /
    defaults: { _controller: "CoavBundle:Reservation:index" }
    methods:  GET

reservation_show:
    path:     /{id}/show
    defaults: { _controller: "CoavBundle:Reservation:show" }
    methods:  GET

reservation_new:
    path:     /new
    defaults: { _controller: "CoavBundle:Reservation:new" }
    methods:  [GET, POST]

reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoavBundle:Reservation:edit" }
    methods:  [GET, POST]

reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoavBundle:Reservation:delete" }
    methods:  DELETE

coav_reservation:
        resource: "@CoavBundle/Resources/config/routing/reservation.yml"
        prefix:   /reservation

